name: Django Tests

on:
    workflow_dispatch:

# on:
#     push:
#         branches: [ "main" ]
#     pull_request:
#         branches: [ "main" ]

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
              python-version: ["3.9", "3.10", "3.11"]
              redis-version: ["5"]
      
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements/dev_ubuntu22.04.txt
            - name: Start Redis
              uses: supercharge/redis-github-action@1.5.0
              with:
                redis-version: ${{ matrix.redis-version }}
                # redis-port: 6379
